// Code generated by ftpl. DO NOT EDIT.
package main

import (
	"github.com/hnamhocit/fiber-template/internal/server"
)

// features wires all registered features with their dependencies.
func features(deps server.Deps) []server.Feature {
	return []server.Feature{
	}
}
